services:
  - type: web
    name: steel-browser
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /v1/health
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: cache
      mountPath: /app/.cache
      sizeGB: 1
    ports:
      - port: 3000
        protocol: TCP
      - port: 3001
        protocol: TCP
      - port: 5173
        protocol: TCP
      - port: 9223
        protocol: TCP 